### ISSUE TITLE
option to ctrl+c active task

### ISSUE THREAD

**Issue by x90skysn3k** [NickSanzotta/scanman#5]
add ability to kill hanging task and skip to next without killing program

**Comment by B34MR** [comment]
partial fix: 
crtl-c added for massscan, msf and nmap
https://github.com/NickSanzotta/scanman/commit/07abe2811941bc0c296784bc1368cb4373f18730

**Comment by B34MR** [comment]
partial fix: 
crtl-c added for getdc
https://github.com/NickSanzotta/scanman/commit/6e7cafb56bf317b432a5a1cf9f55f1f382f2b959

**Comment by B34MR** [comment]
crtl-c added for ew and eg
https://github.com/NickSanzotta/scanman/commit/7f81629e47194ab3075cb87d169690fa28e14b56
